import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateContent, generateConceptImage } from '@/lib/gemini'
import { getPrompt } from '@/lib/prompts'



// Force recompile to ensure updated prompt is used by Next.js cache
export async function POST(req: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const { opportunityId, docType, referenceImage, additionalContext, previousDraft } = body

    if (!opportunityId || !docType) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 })
    }

    // Fetch opportunity and line items
    const { data: opty, error: optyError } = await supabase
      .from('opportunities')
      .select('*')
      .eq('id', opportunityId)
      .single()

    if (optyError || !opty) {
      return NextResponse.json({ error: 'Opportunity not found' }, { status: 404 })
    }

    const { data: lineItems, error: itemsError } = await supabase
      .from('opportunity_line_items')
      .select('*')
      .eq('opportunity_id', opportunityId)

    if (itemsError) {
      return NextResponse.json({ error: 'Error fetching line items' }, { status: 500 })
    }

    // Fetch chat history for Two-Way Knowledge Sync (CAG Approach)
    const { data: chatHistory } = await supabase
      .from('opportunity_chats')
      .select('role, content, created_at, user_email')
      .eq('opportunity_id', opportunityId)
      .order('created_at', { ascending: true })

    let enhancedContext = additionalContext || ""
    if (chatHistory && chatHistory.length > 0) {
      enhancedContext += "\n\n[CRITICAL: OPPORTUNITY CHAT HISTORY (CAG)]\nThe user has had conversations with an AI assistant about this opportunity. You MUST read this chat history to understand any updates, budget cuts, meeting notes, or specific instructions discussed recently. Incorporate this knowledge into the document you are generating.\n"
      chatHistory.forEach(chat => {
        const sender = chat.role === 'user' ? chat.user_email || 'User' : 'Opty AI'
        enhancedContext += `\n[${new Date(chat.created_at).toLocaleString()}] ${sender}:\n${chat.content}\n`
      })
    }

    // Generate and Call Gemini
    let htmlContent = "";
    let prompt = "";
    
    if (docType === 'customer_proposal') {
      const promptPart1 = getPrompt(docType, opty, lineItems || [], 1)
      prompt = promptPart1; // Save part 1 as the prompt used for DB reference
      const contentPart1 = await generateContent(promptPart1, referenceImage, enhancedContext, previousDraft)
      
      const promptPart2 = getPrompt(docType, opty, lineItems || [], 2)
      // For part 2, we shouldn't send the reference image again to save tokens if it's not strictly needed for sections 10-18, 
      // but let's pass it anyway just in case the context is needed.
      const contentPart2 = await generateContent(promptPart2, referenceImage, enhancedContext, previousDraft)
      
      htmlContent = contentPart1 + '\n\n' + contentPart2
    } else {
      prompt = getPrompt(docType, opty, lineItems || [])
      htmlContent = await generateContent(prompt, referenceImage, enhancedContext, previousDraft)
    }

    if (docType === 'concept_art') {
      try {
        let cleanedJsonStr = htmlContent.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
        const parsed = JSON.parse(cleanedJsonStr)
        if (!parsed.image_prompt) throw new Error("AI failed to return an image_prompt")
        
        // Call Imagen 3
        const base64Img = await generateConceptImage(parsed.image_prompt)
        
        // Wrap the Image in HTML
        htmlContent = `<div class="my-8 flex flex-col items-center justify-center w-full bg-white p-6 rounded-xl border border-slate-200 shadow-sm concept-art-container">\n<h3 class="font-semibold text-lg text-slate-800 mb-4">Solution Concept Art</h3>\n<img src="data:image/jpeg;base64,${base64Img}" alt="Solution Concept Art" class="w-full max-w-4xl rounded-lg shadow-md" />\n<p class="text-[10px] text-slate-400 mt-6 italic text-center w-full border-t border-slate-100 pt-3"><span class="font-medium text-emerald-600">Visuals generated by Google Imagen 3</span>. This image is an artistic concept and may not reflect accurate technical specifics.</p>\n</div>`
      } catch (err: any) {
        console.error("Imagen rendering error:", err)
        htmlContent = `<div class="bg-red-50 text-red-600 p-4 rounded-md"><strong>Error generating Image:</strong> ${err.message}</div><pre class="whitespace-pre-wrap text-sm mt-2">${htmlContent}</pre>`
      }
    }

    // Save to database
    const { data: existingDoc } = await supabase
      .from('opportunity_documents')
      .select('id, version')
      .eq('opportunity_id', opportunityId)
      .eq('doc_type', docType)
      .single()

    let result;
    
    if (existingDoc) {
      const { data, error } = await supabase
        .from('opportunity_documents')
        .update({
          content_html: htmlContent,
          prompt_used: prompt,
          generated_by: user.id,
          generated_at: new Date().toISOString(),
          version: existingDoc.version + 1,
          status: 'ready'
        })
        .eq('id', existingDoc.id)
        .select()
      
      if (error) throw error
      result = data[0]
    } else {
      const { data, error } = await supabase
        .from('opportunity_documents')
        .insert([{
          opportunity_id: opportunityId,
          doc_type: docType,
          content_html: htmlContent,
          prompt_used: prompt,
          generated_by: user.id,
          status: 'ready'
        }])
        .select()
        
      if (error) throw error
      result = data[0]
    }

    // Record activity log
    await supabase.from('opportunity_activities').insert([{
      opportunity_id: opportunityId,
      activity_type: 'DOC_GENERATED',
      description: `Generated AI Document: ${docType}`,
      created_by: user.email || 'System'
    }])

    return NextResponse.json({ success: true, document: result })

  } catch (error: any) {
    console.error('API Error:', error)
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
  }
}
