import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateContent, generateConceptImage } from '@/lib/gemini'
import { getPrompt } from '@/lib/prompts'

// Force recompile to ensure updated prompt is used by Next.js cache
export async function POST(req: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const { opportunityId, docType, referenceImage, additionalContext, previousDraft } = body

    if (!opportunityId || !docType) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 })
    }

    // Fetch opportunity and line items
    const { data: opty, error: optyError } = await supabase
      .from('opportunities')
      .select('*')
      .eq('id', opportunityId)
      .single()

    if (optyError || !opty) {
      return NextResponse.json({ error: 'Opportunity not found' }, { status: 404 })
    }

    const { data: lineItems, error: itemsError } = await supabase
      .from('opportunity_line_items')
      .select('*')
      .eq('opportunity_id', opportunityId)

    if (itemsError) {
      return NextResponse.json({ error: 'Error fetching line items' }, { status: 500 })
    }

    // Generate prompt
    const prompt = getPrompt(docType, opty, lineItems || [])

    // Call Gemini
    let htmlContent = await generateContent(prompt, referenceImage, additionalContext, previousDraft)

    if (docType === 'concept_art') {
      try {
        let cleanedJsonStr = htmlContent.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
        const parsed = JSON.parse(cleanedJsonStr)
        if (!parsed.image_prompt) throw new Error("AI failed to return an image_prompt")
        
        // Call Imagen 3
        const base64Img = await generateConceptImage(parsed.image_prompt)
        
        // Wrap the Image in HTML
        htmlContent = `<div class="my-8 flex flex-col items-center justify-center w-full bg-white p-6 rounded-xl border border-slate-200 shadow-sm concept-art-container">\n<h3 class="font-semibold text-lg text-slate-800 mb-4">Solution Concept Art</h3>\n<img src="data:image/jpeg;base64,${base64Img}" alt="Solution Concept Art" class="w-full max-w-4xl rounded-lg shadow-md" />\n<p class="text-[10px] text-slate-400 mt-6 italic text-center w-full border-t border-slate-100 pt-3"><span class="font-medium text-emerald-600">Visuals generated by Google Imagen 3</span>. This image is an artistic concept and may not reflect accurate technical specifics.</p>\n</div>`
      } catch (err: any) {
        console.error("Imagen rendering error:", err)
        htmlContent = `<div class="bg-red-50 text-red-600 p-4 rounded-md"><strong>Error generating Image:</strong> ${err.message}</div><pre class="whitespace-pre-wrap text-sm mt-2">${htmlContent}</pre>`
      }
    }

    // Save to database
    const { data: existingDoc } = await supabase
      .from('opportunity_documents')
      .select('id, version')
      .eq('opportunity_id', opportunityId)
      .eq('doc_type', docType)
      .single()

    let result;
    
    if (existingDoc) {
      const { data, error } = await supabase
        .from('opportunity_documents')
        .update({
          content_html: htmlContent,
          prompt_used: prompt,
          generated_by: user.id,
          generated_at: new Date().toISOString(),
          version: existingDoc.version + 1,
          status: 'ready'
        })
        .eq('id', existingDoc.id)
        .select()
      
      if (error) throw error
      result = data[0]
    } else {
      const { data, error } = await supabase
        .from('opportunity_documents')
        .insert([{
          opportunity_id: opportunityId,
          doc_type: docType,
          content_html: htmlContent,
          prompt_used: prompt,
          generated_by: user.id,
          status: 'ready'
        }])
        .select()
        
      if (error) throw error
      result = data[0]
    }

    return NextResponse.json({ success: true, document: result })

  } catch (error: any) {
    console.error('API Error:', error)
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
  }
}
